In [1]:
from sklearn import datasets, svm

iris = datasets.load_iris()

In [7]:
import pandas as pd

df = pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower'] = iris.target
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df[47:55]

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)      flower
47                4.6               3.2                1.4               0.2      setosa
48                5.3               3.7                1.5               0.2      setosa
49                5.0               3.3                1.4               0.2      setosa
50                7.0               3.2                4.7               1.4  versicolor
51                6.4               3.2                4.5               1.5  versicolor
52                6.9               3.1                4.9               1.5  versicolor
53                5.5               2.3                4.0               1.3  versicolor
54                6.5               2.8                4.6               1.5  versicolor

In [12]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(iris.data,iris.target,train_size=0.7)

In [13]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,y_train)
model.score(X_test,y_test)

0.9555555555555556

In [14]:
from sklearn.model_selection import cross_val_score

In [15]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [16]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [17]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [18]:
import numpy as np

In [33]:
kernel = ['rbf','linear']
C = [1,10,20]
avg_score = {}
for kval in kernel:
    for cval in C:
        cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_score[kval+'_'+ str(cval)] = np.average(cv_scores)
        print(cv_scores)
avg_score

[0.96666667 1.         0.96666667 0.96666667 1.        ]
[0.96666667 1.         0.96666667 0.96666667 1.        ]
[0.96666667 1.         0.9        0.96666667 1.        ]
[0.96666667 1.         0.96666667 0.96666667 1.        ]
[1.         1.         0.9        0.96666667 1.        ]
[1.         1.         0.9        0.93333333 1.        ]


{'rbf_1': np.float64(0.9800000000000001),
 'rbf_10': np.float64(0.9800000000000001),
 'rbf_20': np.float64(0.9666666666666668),
 'linear_1': np.float64(0.9800000000000001),
 'linear_10': np.float64(0.9733333333333334),
 'linear_20': np.float64(0.9666666666666666)}

In [37]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(svm.SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel': ['rbf','linear']
},cv=5)

In [38]:
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.0019979 , 0.00246778, 0.00245934, 0.00184584, 0.00128551,
        0.00108867]),
 'std_fit_time': array([0.00028825, 0.00107903, 0.00041181, 0.00089333, 0.00019132,
        0.00021299]),
 'mean_score_time': array([0.00162477, 0.00168867, 0.00199528, 0.00107746, 0.00090303,
        0.000665  ]),
 'std_score_time': array([1.17486947e-04, 7.29541862e-04, 1.18349658e-03, 4.27347899e-04,
        1.90667534e-04, 4.09764901e-05]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'li

In [39]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.001998      0.000288  ...        0.016330                1
1       0.002468      0.001079  ...        0.016330                1
2       0.002459      0.000412  ...        0.016330                1
3       0.001846      0.000893  ...        0.038873                4
4       0.001286      0.000191  ...        0.036515                5
5       0.001089      0.000213  ...        0.042164                6

[6 rows x 15 columns]

In [40]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667

In [41]:
clf.best_score_

np.float64(0.9800000000000001)

In [42]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [45]:
from sklearn.model_selection import RandomizedSearchCV

rs = RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C': [1,10,20],
    'kernel': ['rbf','linear']
},cv=5,n_iter=2)

In [60]:
rs.fit(iris.data,iris.target)


RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [66]:
df = pd.DataFrame(rs.cv_results_)
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       10          rbf         0.980000
1       10       linear         0.973333

In [67]:
rs.best_params_

{'kernel': 'rbf', 'C': 10}

In [68]:
rs.best_score_

np.float64(0.9800000000000001)

In [74]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [91]:
model_params = {
    'svm' :{
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C': [1,10,20],
            'kernel':['rbf','linear']
        }
    },
    'random_forest':{
        'model': RandomForestClassifier(),
        'params':{
            'n_estimators': [1,5,10]
    }},
    'logistic_regression':{
        'model': LogisticRegression(),
        'params':{
            'C': [1,5,10],
            'max_iter': [200]
        }
    }
}

In [92]:
scores = []

for model_name,mp in model_params.items():
    clf = GridSearchCV(mp['model'],mp['params'],cv=5)
    clf.fit(iris.data,iris.target)
    scores.append({
        'model': model_name,
        'best_score' : clf.best_score_,
        'best_params': clf.best_params_
    })
scores

[{'model': 'svm',
  'best_score': np.float64(0.9800000000000001),
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': np.float64(0.9533333333333334),
  'best_params': {'n_estimators': 5}},
 {'model': 'logistic_regression',
  'best_score': np.float64(0.9733333333333334),
  'best_params': {'C': 1, 'max_iter': 200}}]

In [94]:
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.953333        {'n_estimators': 5}
2  logistic_regression    0.973333  {'C': 1, 'max_iter': 200}