In [25]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [26]:
df = pd.read_csv(r"D:\Carrer\AI\AI Er Learning\ML\14) Naive Bayes Classifier Algorithm\data\spam.csv")
df

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [27]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [28]:
df['spam'] = df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [29]:
X_train,X_test,y_train,y_test = train_test_split(df['Message'],df['spam'],train_size=0.75)

In [30]:
from sklearn.feature_extraction.text import CountVectorizer
v = CountVectorizer()
X_train_count= v.fit_transform(X_train.values)
X_train_count

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 55753 stored elements and shape (4179, 7584)>

In [31]:
len(X_train)

4179

In [32]:
X_train.values

array(['Hey sexy buns! What of that day? No word from you this morning on YM ... :-( ... I think of you',
       'Thats cool. Where should i cum? On you or in you? :)',
       'Anytime...', ..., "No. Thank you. You've been wonderful",
       "What's happening with you. Have you gotten a job and have you begun registration for permanent residency",
       'Well, I have to leave for my class babe ... You never came back to me ... :-( ... Hope you have a nice sleep, my love'],
      shape=(4179,), dtype=object)

In [33]:
type(X_train)

pandas.core.series.Series

In [34]:
type(X_train.values)

numpy.ndarray

In [35]:
X_train_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4179, 7584))

In [36]:
X_train_count

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 55753 stored elements and shape (4179, 7584)>

In [37]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count,y_train)

MultinomialNB()

In [38]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]
emails_count = v.transform(emails)
emails_count

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 22 stored elements and shape (2, 7584)>

In [39]:
model.predict(emails_count)

array([0, 1])

In [40]:
X_test_count = v.transform(X_test)
model.score(X_test_count,y_test)

0.9842067480258435

In [41]:
from sklearn.pipeline import Pipeline

clf = Pipeline([
    ('vectorizer',CountVectorizer()),
    ('nb',MultinomialNB())
])

In [42]:
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.9842067480258435

In [43]:
clf.predict(emails)

array([0, 1])