In [4]:
import numpy as np

In [6]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [26]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)
    
    

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [21]:
for col in a:
    print(col)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [34]:
for x in np.nditer(a,order='C',op_flags=['readwrite']):
    x[...]=x+1

In [35]:
a


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [36]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [37]:
for x in np.nditer(a,order='C',op_flags=['readwrite']):
    x[...]=x+2

In [38]:
a

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [39]:
for x in np.nditer(a,order='C',op_flags=['readwrite']):
    x[...]=x*x

In [40]:
a

array([[  4,   9,  16,  25],
       [ 36,  49,  64,  81],
       [100, 121, 144, 169]])

In [41]:
a

array([[  4,   9,  16,  25],
       [ 36,  49,  64,  81],
       [100, 121, 144, 169]])

In [49]:
b = np.arange(3,19,5).reshape(4,1)

In [50]:
b

array([[ 3],
       [ 8],
       [13],
       [18]])

In [51]:
for x,y in np.nditer([a,b]):
    print(x,y)


ValueError: operands could not be broadcast together with shapes (3,4) (4,1) 