In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
import pandas as pd
from sklearn.datasets import load_digits


digits = load_digits()

In [5]:
df = pd.DataFrame(digits.data,columns=digits.feature_names)
df.head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_5  pixel_7_6  pixel_7_7
0        0.0        0.0        5.0  ...        0.0        0.0        0.0
1        0.0        0.0        0.0  ...       10.0        0.0        0.0
2        0.0        0.0        0.0  ...       16.0        9.0        0.0
3        0.0        0.0        7.0  ...        9.0        0.0        0.0
4        0.0        0.0        0.0  ...        4.0        0.0        0.0

[5 rows x 64 columns]

In [3]:
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [4]:
digits.feature_names

['pixel_0_0',
 'pixel_0_1',
 'pixel_0_2',
 'pixel_0_3',
 'pixel_0_4',
 'pixel_0_5',
 'pixel_0_6',
 'pixel_0_7',
 'pixel_1_0',
 'pixel_1_1',
 'pixel_1_2',
 'pixel_1_3',
 'pixel_1_4',
 'pixel_1_5',
 'pixel_1_6',
 'pixel_1_7',
 'pixel_2_0',
 'pixel_2_1',
 'pixel_2_2',
 'pixel_2_3',
 'pixel_2_4',
 'pixel_2_5',
 'pixel_2_6',
 'pixel_2_7',
 'pixel_3_0',
 'pixel_3_1',
 'pixel_3_2',
 'pixel_3_3',
 'pixel_3_4',
 'pixel_3_5',
 'pixel_3_6',
 'pixel_3_7',
 'pixel_4_0',
 'pixel_4_1',
 'pixel_4_2',
 'pixel_4_3',
 'pixel_4_4',
 'pixel_4_5',
 'pixel_4_6',
 'pixel_4_7',
 'pixel_5_0',
 'pixel_5_1',
 'pixel_5_2',
 'pixel_5_3',
 'pixel_5_4',
 'pixel_5_5',
 'pixel_5_6',
 'pixel_5_7',
 'pixel_6_0',
 'pixel_6_1',
 'pixel_6_2',
 'pixel_6_3',
 'pixel_6_4',
 'pixel_6_5',
 'pixel_6_6',
 'pixel_6_7',
 'pixel_7_0',
 'pixel_7_1',
 'pixel_7_2',
 'pixel_7_3',
 'pixel_7_4',
 'pixel_7_5',
 'pixel_7_6',
 'pixel_7_7']

In [6]:
digits.data.shape

(1797, 64)

In [7]:
df['target'] = digits.target
df

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_6  pixel_7_7  target
0           0.0        0.0        5.0  ...        0.0        0.0       0
1           0.0        0.0        0.0  ...        0.0        0.0       1
2           0.0        0.0        0.0  ...        9.0        0.0       2
3           0.0        0.0        7.0  ...        0.0        0.0       3
4           0.0        0.0        0.0  ...        0.0        0.0       4
...         ...        ...        ...  ...        ...        ...     ...
1792        0.0        0.0        4.0  ...        0.0        0.0       9
1793        0.0        0.0        6.0  ...        0.0        0.0       0
1794        0.0        0.0        1.0  ...        0.0        0.0       8
1795        0.0        0.0        2.0  ...        0.0        0.0       9
1796        0.0        0.0       10.0  ...        1.0        0.0       8

[1797 rows x 65 columns]

In [8]:
X = df.drop(['target'],axis='columns')
X.head()

pixel_0_0  pixel_0_1  pixel_0_2  ...  pixel_7_5  pixel_7_6  pixel_7_7
0        0.0        0.0        5.0  ...        0.0        0.0        0.0
1        0.0        0.0        0.0  ...       10.0        0.0        0.0
2        0.0        0.0        0.0  ...       16.0        9.0        0.0
3        0.0        0.0        7.0  ...        9.0        0.0        0.0
4        0.0        0.0        0.0  ...        4.0        0.0        0.0

[5 rows x 64 columns]

In [9]:
y = df['target']
y

0       0
1       1
2       2
3       3
4       4
       ..
1792    9
1793    0
1794    8
1795    9
1796    8
Name: target, Length: 1797, dtype: int64

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7)

In [17]:
lr = LogisticRegression(max_iter=200)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9629629629629629

In [18]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [20]:
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9796296296296296

In [51]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [52]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [53]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [55]:
get_score(LogisticRegression(max_iter=150),X_train,X_test,y_train,y_test)

0.9629629629629629

In [58]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits = 3)

In [88]:
scores_lr = []
score_svm = []
score_rf = []
for train_index,test_index in folds.split(X,y):
    X_train,X_test,y_train,y_test = X.iloc[train_index],X.iloc[test_index],y.iloc[train_index],y.iloc[test_index]
    scores_lr.append(get_score(LogisticRegression(max_iter=150),X_train,X_test,y_train,y_test))
    score_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))
    

In [89]:
scores_lr

[0.9198664440734557, 0.9415692821368948, 0.9165275459098498]

In [90]:
score_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

In [91]:
score_rf

[0.9248747913188647, 0.9499165275459098, 0.9315525876460768]

In [103]:
from sklearn.model_selection import cross_val_score

cross_val_score(LogisticRegression(max_iter=200),X,y,cv=3)

array([0.91986644, 0.94156928, 0.91652755])

In [105]:
cross_val_score(SVC(),X,y,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [115]:
cross_val_score(RandomForestClassifier(n_estimators=40),X,y,cv=3)

array([0.92487479, 0.94991653, 0.93155259])

In [116]:
cross_val_score(RandomForestClassifier(n_estimators=10),X,y,cv=3)

array([0.89315526, 0.92153589, 0.87813022])

In [117]:
cross_val_score(RandomForestClassifier(n_estimators=40),X,y,cv=3)

array([0.92320534, 0.94490818, 0.9148581 ])